/*
 * Copyright (c) 2024 Analog Devices Inc.
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#ifndef ZEPHYR_INCLUDE_DRIVERS_SENSOR_MAX30123_H_
#define ZEPHYR_INCLUDE_DRIVERS_SENSOR_MAX30123_H_

#include <zephyr/drivers/sensor.h>

/* Start SEQUENCER enum at SENSOR_CHAN_PRIV_START */
enum sensor_channel_max30123 {
	SENSOR_CHAN_ECS_SEQUENCER_1 = SENSOR_CHAN_PRIV_START,
	SENSOR_CHAN_ECS_SEQUENCER_2,
	SENSOR_CHAN_ECS_SEQUENCER_3,
	SENSOR_CHAN_ECS_SEQUENCER_4,
	SENSOR_CHAN_ECS_SEQUENCER_5,
	SENSOR_CHAN_ECS_SEQUENCER_6,
};

#endif /* ZEPHYR_INCLUDE_DRIVERS_SENSOR_MAX30123_H_ */
