name: Manifest
on:
  pull_request_target:

jobs:
  contribs:
    runs-on: ses-edi-build-lu-x64-10
    name: Manifest
    steps:
      - name: Remove Possible Existing Access Token
        continue-on-error: true
        run: |
          # Token is generated at the run time and at the end of process it is expires,
          # storing it in global config causes duplication line in config file
          # so that possible existing one shall be deleted before generating new one
          # otherwiser autantication will be failed.
          existingTokenURL=$(git config --global --get-regexp url.*@github.com/.insteadOf)
          echo "All Token:${existingTokenURL}"
          for item in $(echo ${existingTokenURL}); do
            if [ ${item} == "https://github.com/" ]; then
              continue
            fi
            echo "Removing: ${item}"
            git config --global --unset-all "${item}"
          done

      - name: Get Access Token
        id: generate-github-app-token
        uses: adi-innersource/shared-actions/generate-github-token@v1
        with:
          app-id: ${{ secrets.TOKEN_GENERATOR_APP_ID }}
          private-key: ${{ secrets.TOKEN_GENERATOR_APP_PRIVATE_KEY }}
          organization: ${{ github.repository_owner }}
          repositories: |
            zephyr
            zephyr-runner-configurations
            hal_adi
            packetcraft-adi
            trusted-firmware-m
            trusted-firmware-a
            tf-m-tests
            psa-arch-tests

      - name: Checkout the code
        uses: actions/checkout@v4
        with:
          path: zephyrproject/zephyr
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
          persist-credentials: false

      - name: west setup
        env:
          BASE_REF: ${{ github.base_ref }}
          ACCESS_TOKEN: ${{ steps.generate-github-app-token.outputs.access-token }}
        working-directory: zephyrproject/zephyr
        run: |
          pip3 install west
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          git config --global url."https://${ACCESS_TOKEN}:${ACCESS_TOKEN}@github.com/".insteadOf "https://github.com/"
          west init -l . || true
          # Remove token that used by this session
          git config --global --unset-all url."https://${ACCESS_TOKEN}:${ACCESS_TOKEN}@github.com/".insteadOf

      - name: Manifest
        uses: zephyrproject-rtos/action-manifest@v1.3.1
        with:
          github-token: ${{ steps.generate-github-app-token.outputs.access-token }}
          manifest-path: 'west.yml'
          checkout-path: 'zephyrproject/zephyr'
          use-tree-checkout: 'true'
          check-impostor-commits: 'true'
          label-prefix: 'manifest-'
          verbosity-level: '1'
          labels: 'manifest'
          dnm-labels: 'DNM'
